### ISSUE TITLE
Unnecessary branching, force allocation of power of 2

### ISSUE THREAD

**Issue by hbina** [drogalis/SPSC-Queue#2]
https://github.com/drogalis/SPSC-Queue/blob/14b970bfb501d36888e818ecb05ecac0905bdd13/include/dro/spsc-queue.hpp#L162

**Comment by drogalis** [comment]
In large queues, the branch predictor has no problem with this since `capacity_ - 1` times it will just be an increment, and only (1 / capacity_) % of the time will it be 0.

I ran benchmarks and the extra bit wise operation every single time has a negative performance impact.
